# syntax=docker/dockerfile:1

# Base images with pre-installed Snyk CLI and common dependencies

FROM ubuntu:latest AS snyk-base-ubuntu
ARG CLI_VERSION=latest
ENV SNYK_CLI_VERSION=$CLI_VERSION

# Install all common dependencies in one layer
RUN apt-get update \
    && apt-get install -y \
    curl \
    python3 \
    python3-requests \
    && apt-get auto-remove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Install Snyk CLI
RUN curl --compressed --output /usr/local/bin/install-snyk.py https://raw.githubusercontent.com/snyk/cli/main/scripts/install-snyk.py \
    && chmod +x /usr/local/bin/install-snyk.py \
    && install-snyk.py $SNYK_CLI_VERSION

FROM alpine:latest AS snyk-base-alpine
ARG CLI_VERSION=latest
ENV SNYK_CLI_VERSION=$CLI_VERSION

# Install all common dependencies in one layer
RUN apk update \
    && apk add --no-cache \
    curl \
    python3 \
    py3-requests

# Install Snyk CLI
RUN curl --compressed --output /usr/local/bin/install-snyk.py https://raw.githubusercontent.com/snyk/cli/main/scripts/install-snyk.py \
    && chmod +x /usr/local/bin/install-snyk.py \
    && install-snyk.py $SNYK_CLI_VERSION
