name: Build Base Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1" # Every Monday at 2 AM UTC
  push:
    paths:
      - "Dockerfile.base"
      - ".github/workflows/base-images.yml"

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_type: [ ubuntu, alpine ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.base
          target: snyk-base-${{ matrix.base_type }}
          tags: snyk/snyk:base-${{ matrix.base_type }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CLI_VERSION=latest
